# Generated by Django 5.1.3 on 2024-12-15 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='amount_limit',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(limit_choices_to={'category_type': 'Expense'}, on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='home_app.category'),
        ),
        migrations.AlterField(
            model_name='emi',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='overallbudget',
            name='amount_limit',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
