# Generated by Django 5.1.3 on 2024-12-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_alter_budget_amount_limit_alter_budget_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emi',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
