# Generated by Django 5.1.3 on 2024-12-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_emi_last_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emi',
            name='next_payment_date',
            field=models.DateField(null=True),
        ),
    ]
